from tokyo_lineage.metadata_extractor.airflow import PostgresExtractor, PostgresToAvroExtractor, FileToGcsExtractor

AIRFLOW_EXTRACTORS = [PostgresExtractor, PostgresToAvroExtractor, FileToGcsExtractor]