from tokyo_lineage.metadata_extractor.airflow import PostgresExtractor, PostgresToAvroExtractor, FileToGcsExtractor, GcsToBigQueryExtractor

AIRFLOW_EXTRACTORS = [PostgresExtractor, PostgresToAvroExtractor, FileToGcsExtractor, GcsToBigQueryExtractor]